### ISSUE TITLE
Chat - client side

### ISSUE THREAD

**Issue by vermi4elli** [TheBestTvarynka/ubiquitous-spark#11]
Finish functionality:
- check the db for the existence of the chat (if not, then create; if exists, just render the page)
- rewrite the render part to work with sockets and get history from db:
             1. create socket
             2. onopen - send socket to base with request and message
             3. message structure for history: { title: history, time: new Date() }
             4. message structure for uploading: { title: message, chat_id: -, author: -, message: -, time: new Date() }
             5. onmessage: all data I've received is going into html
- incoming history structure: { messages: [ { author: -, message: -, time: - }, {}, ... ] }
- incoming message structure: { reply: { author: -, message: -, time: - } }

**Comment by vermi4elli** [comment]
#10

**Comment by TheBestTvarynka** [comment]
#10
